server:
  port: 8080
  servlet:
    contextPath: /api/v1
  error:
    include-message: always
    include-stacktrace: never

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tour_management
    username: root
    password: That123
  jpa:
    hibernate:
      ddl-auto: update
  main:
    web-application-type: servlet
    banner-mode: off

logging:
  level:
    root: warn

app:
  url: http://localhost:8080