server:
  port: 8080
  servlet:
    contextPath: /api/v1
  error:
    include-message: always
    include-stacktrace: never

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tour_management
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
  main:
    web-application-type: servlet
    banner-mode: off
  security:
    user:
      alwaysGenerateLoginUsername: false

logging:
  level:
    root: warn

jwt:
  access:
    key: u344qp/MlRfLr2iwJbnCntS1yqUpS7EULBUkoUuU+JI=
  refresh:
    key: t/bl0PnTRZ1C+Qa7OrOP8MMEfU2F1kdCAy+7GKR1O+o=

app:
  url: http://localhost:8080