server:
  port: 8080
  servlet:
    contextPath: /api/v1
  error:
    include-message: always
    include-stacktrace: never

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tour_management
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
  main:
    web-application-type: servlet
    banner-mode: off
  security:
    user:
      alwaysGenerateLoginUsername: false

logging:
  level:
    root: warn

token:
  signing:
    key: wJ6L+8JGZFHY6iPEp7LswQqKR1HJ/XYNE8mU9L7BBCE=


app:
  url: http://localhost:8080