server:
  port: 8080
  servlet:
    contextPath: /api/v1
  error:
    include-message: always
    include-stacktrace: never

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tour_management
    username: root
    password: minhhieu
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  main:
    web-application-type: servlet
    banner-mode: off
  mail:
    host: smtp.gmail.com
    port: 587
    username: truongvanhao159@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


jwt:
  access:
    key: u344qp/MlRfLr2iwJbnCntS1yqUpS7EULBUkoUuU+JI=
  refresh:
    key: t/bl0PnTRZ1C+Qa7OrOP8MMEfU2F1kdCAy+7GKR1O+o=

app:
  url: http://localhost:8080